// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbm7BiFTK_W-THiwp3TXyoYSwKlNDXWOc',
    appId: '1:582642237743:web:ce7d2fa30efac6274221da',
    messagingSenderId: '582642237743',
    projectId: 'car-park-a14e2',
    authDomain: 'car-park-a14e2.firebaseapp.com',
    databaseURL: 'https://car-park-a14e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-park-a14e2.appspot.com',
    measurementId: 'G-GPB0T4HRXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh-kNLQn_H8Z6bpSlADtrSRGFdi_dbPn4',
    appId: '1:582642237743:android:b9b6ac2486d927124221da',
    messagingSenderId: '582642237743',
    projectId: 'car-park-a14e2',
    databaseURL: 'https://car-park-a14e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-park-a14e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy1080gUPOweGO7Aq5rVBrQiVLcGgVR18',
    appId: '1:582642237743:ios:af3c658775b43d2b4221da',
    messagingSenderId: '582642237743',
    projectId: 'car-park-a14e2',
    databaseURL: 'https://car-park-a14e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-park-a14e2.appspot.com',
    iosBundleId: 'com.example.carPark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy1080gUPOweGO7Aq5rVBrQiVLcGgVR18',
    appId: '1:582642237743:ios:af3c658775b43d2b4221da',
    messagingSenderId: '582642237743',
    projectId: 'car-park-a14e2',
    databaseURL: 'https://car-park-a14e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'car-park-a14e2.appspot.com',
    iosBundleId: 'com.example.carPark',
  );
}
